sudo: required
services: docker
language: go
install: true

#Update to last docker engine
before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-engine
  
before_script:
  - if ! [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then export DOCKER_USERNAME=""; export DOCKER_PASSWORD=""; fi
  - go get -u -v github.com/estesp/manifest-tool
  
script:
  - echo "ok"
  - bash gitea/build.sh

after_success:
  - $GOPATH/bin/manifest-tool --username $DOCKER_USERNAME --password $DOCKER_PASSWORD push from-spec alpine-multi/alpine-multi.yml
  - $GOPATH/bin/manifest-tool --username $DOCKER_USERNAME --password $DOCKER_PASSWORD push from-spec alpine-multi/alpine-multi-edge.yml
  - $GOPATH/bin/manifest-tool --username $DOCKER_USERNAME --password $DOCKER_PASSWORD push from-spec alpine-multi/alpine-multi-3-5.yml
